DEBUG    BddScenarioTests:abstract_tests_base.py:70 setup
DEBUG    BddScenarioTests:abstract_tests_base.py:63 initiating <class 'qa_pytest_commons.generic_steps.GenericSteps'>
DEBUG    GenericSteps:logger.py:130 >>> given  
DEBUG    GenericSteps:logger.py:143 <<< given
DEBUG    GenericSteps:logger.py:130 >>> nothing  
DEBUG    GenericSteps:logger.py:143 <<< nothing
DEBUG    GenericSteps:logger.py:130 >>> when  
DEBUG    GenericSteps:logger.py:143 <<< when
DEBUG    GenericSteps:logger.py:130 >>> safely <function BddScenarioTests.should_swallow_exception.<locals>.<lambda> at 0x7f49cf481120> 
DEBUG    GenericSteps:logger.py:130 >>> when  
DEBUG    GenericSteps:logger.py:143 <<< when
DEBUG    GenericSteps:logger.py:130 >>> failing boom 
ERROR    root:exception_utils.py:30 Exception occurred: boom
Traceback (most recent call last):
  File "/home/runner/work/qa-automation-python/qa-automation-python/qa-testing-utils/src/qa_testing_utils/exception_utils.py", line 27, in safely
    result = supplier()
  File "/home/runner/work/qa-automation-python/qa-automation-python/qa-pytest-commons/src/qa_pytest_commons/generic_steps.py", line 265, in <lambda>
    return safely(lambda: step()).value_or(self)
                          ~~~~^^
  File "/home/runner/work/qa-automation-python/qa-automation-python/qa-pytest-commons/tests/bdd_scenario_tests.py", line 38, in <lambda>
    .when.safely(lambda: self.steps.when.failing(TestException("boom")))
                         ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/qa-automation-python/qa-automation-python/qa-testing-utils/src/qa_testing_utils/logger.py", line 140, in wrapper
    result = func(*args, **kwargs)
  File "/home/runner/work/qa-automation-python/qa-automation-python/qa-pytest-commons/src/qa_pytest_commons/generic_steps.py", line 233, in failing
    raise exception
qa_testing_utils.exceptions.TestException: boom
DEBUG    GenericSteps:logger.py:143 <<< safely
DEBUG    GenericSteps:logger.py:130 >>> then  
DEBUG    GenericSteps:logger.py:143 <<< then
DEBUG    GenericSteps:logger.py:130 >>> it_works <True> 
DEBUG    GenericSteps:logger.py:143 <<< it_works
DEBUG    BddScenarioTests:abstract_tests_base.py:76 teardown