DEBUG    SelfTests:self_tests.py:28 before <bound method SelfTests.should_retry of <tests.self_tests.SelfTests object at 0x7f832908d040>>
DEBUG    SelfTests:before_sleep.py:65 Retrying tests.self_tests.SelfTests.should_retry.<locals>.do_something_unreliable in 0.001 seconds as it raised TestException: failed.
DEBUG    SelfTests:self_tests.py:31 after <bound method SelfTests.should_retry of <tests.self_tests.SelfTests object at 0x7f832908d040>>